package com.cgd.client_check.model;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class EvaluationReview implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "Review List")
	private java.util.List<com.cgd.client_check.model.Review> reviewList;

	public EvaluationReview() {
	}

	public java.util.List<com.cgd.client_check.model.Review> getReviewList() {
		return this.reviewList;
	}

	public void setReviewList(
			java.util.List<com.cgd.client_check.model.Review> reviewList) {
		this.reviewList = reviewList;
	}

	public EvaluationReview(
			java.util.List<com.cgd.client_check.model.Review> reviewList) {
		this.reviewList = reviewList;
	}
	
    @Override
    public String toString() {
        return "EvaluationReview{" +
                "reviewList=" + reviewList +
                '}';
    }
}