package com.cgd.client_check.model;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Review implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "Analyst")
	private java.lang.String analyst;
	@org.kie.api.definition.type.Label(value = "Result")
	private java.lang.String result;
	@org.kie.api.definition.type.Label(value = "Comment")
	private java.lang.String comment;

	public Review() {
	}

	public java.lang.String getAnalyst() {
		return this.analyst;
	}

	public void setAnalyst(java.lang.String analyst) {
		this.analyst = analyst;
	}

	public java.lang.String getResult() {
		return this.result;
	}

	public void setResult(java.lang.String result) {
		this.result = result;
	}

	public java.lang.String getComment() {
		return this.comment;
	}

	public void setComment(java.lang.String comment) {
		this.comment = comment;
	}

	public Review(java.lang.String analyst, java.lang.String result,
			java.lang.String comment) {
		this.analyst = analyst;
		this.result = result;
		this.comment = comment;
	}
	
	@Override
    public String toString() {
        return "Review{" +
                "analyst='" + analyst + '\'' +
                ", result='" + result + '\'' +
                ", comment='" + comment + '\'' +
                '}';
    }

}